name: Deploy to Salesforce (JWT)

on:
  push:
    branches:
      - master  # 실제 사용하는 브랜치 이름으로 변경 가능 (예: main)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1  # 공식 GitHub 액션 추천

      - name: Create server.key from Secret
        run: echo "${{ secrets.SF_JWT_KEY }}" > server.key

      - name: Set file permissions for server.key
        run: chmod 600 server.key

      - name: Authenticate to Salesforce (JWT)
        run: |
          sfdx force:auth:jwt:grant
            --clientid "${{ secrets.SF_CONSUMER_KEY }}"
            --jwtkeyfile server.key
            --username "${{ secrets.SF_USERNAME }}"
            --instanceurl https://login.salesforce.com
            --setdefaultusername

      - name: Deploy to Salesforce
        run: |
          sfdx force:source:deploy
            -p force-app
            --testlevel RunLocalTests
            --json > deploy-result.json

      - name: Show Deployment Result (if failed)
        if: failure()
        run: cat deploy-result.json || true

      - name: Upload Deployment Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: deploy-report
          path: deploy-result.json
