name: Salesforce Deploy

on:
  push:
    branches:
      - master  # 필요 시 main으로 수정

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: npm install -g sfdx-cli

      - name: Generate server.key file
        run: echo "${{ secrets.SALESFORCE_SERVER_KEY }}" > server.key

      - name: Authenticate to Salesforce using JWT
        run: |
          sfdx force:auth:jwt:grant \
            --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} \
            --jwtkeyfile server.key \
            --username ${{ secrets.SALESFORCE_USERNAME }} \
            --instanceurl https://login.salesforce.com \
            --setdefaultusername

      - name: Deploy source to Salesforce
        run: |
          sfdx force:source:deploy -p force-app -u ${{ secrets.SALESFORCE_USERNAME }}
