name: Deploy to Salesforce (JWT)

on:
  push:
    branches: [ "master" ]  # 필요시 main 등으로 변경
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Salesforce CLI (sf)
        run: npm install --global @salesforce/cli

      - name: Write server.key from GitHub Secret
        run: |
          echo "${{ secrets.SALESFORCE_SERVER_KEY }}" > server.key
          chmod 600 server.key

      - name: Authenticate with Salesforce using JWT
        run: |
          sf org login jwt \
            --client-id "${{ secrets.SALESFORCE_CONSUMER_KEY }}" \
            --jwt-key-file server.key \
            --username "${{ secrets.SALESFORCE_USERNAME }}" \
            --instance-url "https://login.salesforce.com" \
            --set-default

      - name: Verify Auth Connection
        run: sf org display --verbose

      - name: Deploy updated source (includes Codex enhancements)
        run: |
          sf project deploy start \
            --source-dir force-app \
            --ignore-conflicts \
            --test-level NoTestRun \
            --json

      # Optional: Add Codex-specific validations or commands here
      # - name: Run Codex lint/validation (if CLI or script available)
      #   run: your-codex-validation-command
