name: Deploy to Salesforce (JWT)

on:
  push:
    branches: [ "master" ]  # 필요 시 main 등으로 변경

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Salesforce CLI (sf)
        run: npm install --global @salesforce/cli

      - name: Write server.key from GitHub Secret
        run: |
          echo "${{ secrets.SALESFORCE_SERVER_KEY }}" > server.key
          chmod 600 server.key

      - name: JWT Auth (sf org login jwt)
        run: |
          sf org login jwt \
            --client-id "${{ secrets.SALESFORCE_CONSUMER_KEY }}" \
            --jwt-key-file server.key \
            --username "${{ secrets.SALESFORCE_USERNAME }}" \
            --instance-url "https://login.salesforce.com" \
            --set-default
      # 참고: JWT Bearer Flow는 CI에 적합한 무인 인증 방식입니다.

      - name: Verify Auth
        run: sf org display --verbose

      - name: Deploy source (force-app)
        run: |
          sf project deploy start \
            --source-dir force-app \
            --ignore-conflicts \
            --test-level NoTestRun \
            --json
name: Deploy to Salesforce (JWT)

on:
  push:
    branches: [ "master" ]  # 필요 시 main 등으로 변경

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Salesforce CLI (sf)
        run: npm install --global @salesforce/cli

      - name: Write server.key from GitHub Secret
        run: |
          echo "${{ secrets.SALESFORCE_SERVER_KEY }}" > server.key
          chmod 600 server.key

      - name: JWT Auth (sf org login jwt)
        run: |
          sf org login jwt \
            --client-id "${{ secrets.SALESFORCE_CONSUMER_KEY }}" \
            --jwt-key-file server.key \
            --username "${{ secrets.SALESFORCE_USERNAME }}" \
            --instance-url "https://login.salesforce.com" \
            --set-default
      # 참고: JWT Bearer Flow는 CI에 적합한 무인 인증 방식입니다.

      - name: Verify Auth
        run: sf org display --verbose

      - name: Deploy source (force-app)
        run: |
          sf project deploy start \
            --source-dir force-app \
            --ignore-conflicts \
            --test-level NoTestRun \
            --json
