name: Deploy to Salesforce (JWT)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI (sf)
        run: |
          npm install @salesforce/cli --global

      - name: Create server.key from Secret
        run: echo "${{ secrets.SF_JWT_KEY }}" > server.key

      - name: Set permissions for server.key
        run: chmod 600 server.key

      - name: Authenticate to Salesforce using JWT
        run: |
          sf org login jwt \
            --client-id ${{ secrets.SF_CONSUMER_KEY }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_USERNAME }} \
            --instance-url https://login.salesforce.com \
            --set-default

      - name: Deploy to Salesforce
        run: |
          sf project deploy start \
            --source-dir force-app \
            --test-level RunLocalTests \
            --json > deploy-result.json

      - name: Show Deployment Result (if failed)
        if: failure()
        run: cat deploy-result.json || true

      - name: Upload Deployment Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: deploy-report
          path: deploy-result.json
