name: Deploy to Salesforce (JWT)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: npm install --global sfdx-cli

      - name: Create server.key from Secret
        run: echo "${{ secrets.SF_JWT_KEY }}" > server.key

      - name: Authenticate to Salesforce (JWT)
        run: |
          sfdx force:auth:jwt:grant \
            --clientid ${{ secrets.SF_CONSUMER_KEY }} \
            --jwtkeyfile server.key \
            --username ${{ secrets.SF_USERNAME }} \
            --instanceurl https://login.salesforce.com \
            --setdefaultusername

      - name: Deploy to Salesforce
        run: |
          sfdx force:source:deploy \
            -p force-app \
            --testlevel RunLocalTests \
            --json > deploy-result.json

      - name: Show Deployment Result (if failed)
        if: failure()
        run: cat deploy-result.json || true
