name: Deploy to Salesforce (JWT - sfdx)

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Salesforce CLI (sfdx)
        run: npm install --global sfdx-cli

      - name: Write server.key from GitHub Secret
        run: |
          echo "${{ secrets.SALESFORCE_SERVER_KEY }}" > server.key
          chmod 600 server.key

      - name: JWT Auth (sfdx)
        run: |
          sfdx force:auth:jwt:grant \
            --client-id "${{ secrets.SALESFORCE_CONSUMER_KEY }}" \
            --jwt-key-file server.key \
            --username "${{ secrets.SALESFORCE_USERNAME }}" \
            --instance-url "https://login.salesforce.com" \
            --set-default-username

      - name: Deploy (sfdx)
        run: |
          sfdx force:source:deploy \
            -p force-app \
            -l NoTestRun \
            -w 33
